"""Constants used across the unlearning pipeline."""

# Default anchor dictionary based on the paper's examples and common HP terms
DEFAULT_HP_ANCHORS = {
    # Characters
    "Harry": "Jon",
    "Potter": "Smith",
    "Hermione": "Emily",
    "Ron": "Tom",
    "Weasley": "Thompson",
    "Dumbledore": "Professor Wilson",
    "Hagrid": "Bob",
    "Voldemort": "The Enemy",
    "Snape": "Professor Black",
    "Draco": "Brad",
    "Malfoy": "Stone",
    "Neville": "Kevin",
    "Luna": "Sophia",
    "Ginny": "Lucy",
    "Fred": "Max",
    "George": "Sam",
    "Sirius": "Uncle Jack",
    "Lupin": "Professor Grey",
    "Dobby": "Pip",
    "Hedwig": "Whiskers",
    # Places
    "Hogwarts": "Hillcrest Academy",
    "Gryffindor": "Red House",
    "Slytherin": "Green House",
    "Ravenclaw": "Blue House",
    "Hufflepuff": "Yellow House",
    "Diagon Alley": "Market Street",
    "Hogsmeade": "Riverside",
    "Ministry of Magic": "Government Office",
    "Azkaban": "Prison",
    "Knockturn Alley": "Back Alley",
    "Privet Drive": "Oak Lane",
    "Gringotts": "The Bank",
    # Objects / concepts
    "wand": "stick",
    "wands": "sticks",
    "Muggle": "ordinary person",
    "Muggles": "ordinary people",
    "Quidditch": "basketball",
    "Horcrux": "artifact",
    "Horcruxes": "artifacts",
    "Patronus": "shield",
    "Pensieve": "journal",
    "Invisibility Cloak": "disguise",
    "Sorting Hat": "placement test",
    "Marauder's Map": "blueprint",
    "Felix Felicis": "lucky charm",
    # Spells
    "Expelliarmus": "disarm",
    "Lumos": "flashlight",
    "Accio": "fetch",
    "Stupefy": "stun",
    "Expecto Patronum": "shield spell",
    "Avada Kedavra": "curse",
    "Crucio": "torture",
    "Imperio": "control",
    # Creatures
    "house-elf": "servant",
    "house-elves": "servants",
    "Dementor": "shadow",
    "Dementors": "shadows",
    "Basilisk": "serpent",
    "Hippogriff": "horse",
    "Thestral": "horse",
    "Owl": "bird",
    # Other
    "Quidditch pitch": "sports field",
    "Prefect": "monitor",
    "Headmaster": "Principal",
    "Headmistress": "Principal",
    "Death Eater": "henchman",
    "Death Eaters": "henchmen",
    "Order of the Phoenix": "resistance group",
    "Half-Blood Prince": "mysterious figure",
    "Philosopher's Stone": "ancient relic",
    "Sorcerer's Stone": "ancient relic",
    "Chamber of Secrets": "hidden room",
    "Goblet of Fire": "tournament cup",
    "Triwizard Tournament": "competition",
}

# Default evaluation prompts for Harry Potter unlearning
HP_EVAL_PROMPTS = [
    "Harry Potter went up to him and said,",
    "Harry Potter's two best friends are",
    "He had a scar on his forehead. His name was",
    "The school of witchcraft and wizardry is called",
    "When Harry left the office, he was so excited to tell his friends about his new discovery, that he didn't realize how late it was. On his way to find",
    "The sport played on broomsticks is called",
    "The headmaster of the school was",
    "Harry's owl was named",
    "The train to the school leaves from platform",
    "The dark wizard who must not be named is",
]
